# Generated by Django 4.2.8 on 2023-12-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_codes',
            field=models.ManyToManyField(related_name='products', through='shop.ProductPromoCodeRelation', to='shop.promocode'),
        ),
    ]
